### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by e64462** [rafradek/sigsegv-mvm#53]
Won't compile on Ubuntu 22.04

https://pastebin.com/5bc4Gdme

ctrl + f "error"

in short:

custom_attributes.cpp:9261:118: error: no matching function for call to ‘GetAddrOfMemberFunc(void (Mod::Attr::Custom_Attributes::Detour_CUpgrades_PlayerPurchasingUpgrade::*)(CTFPlayer*, int, int, bool, bool, bool))’

**Comment by rowedahelicon** [comment]
Needs updated GCC

**Comment by rafradek** [comment]
yeah gcc 13 is required
